#include "a2lite_bf592.h"

#include <stdio.h>
#include <string.h>


/* =============================================================
 * Model geometry
 * ============================================================= */

static const uint8_t K[A2LITE_LAYERS] =
{
    6, 6, 6, 6, 6, 6, 6,
    6, 6, 6, 6, 6, 6, 6,
    15, 15,
    6, 6, 6, 6, 6, 6, 6
};

static const uint16_t D[A2LITE_LAYERS] =
{
    1, 3, 7, 17, 41, 101, 239,
    1, 3, 7, 17, 41, 101, 239,
    1, 13,
    1, 3, 7, 17, 41, 101, 239
};


/*
 * These are generated by the validated 2.6 reference.
 *
 * For the current A2-Lite model every required shift is zero.
 *
 * Keeping them explicit is important: the runtime does not
 * silently invent scaling.
 */
static const uint8_t LAYER_SHIFT[A2LITE_LAYERS] =
{
    0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0,
    0, 0,
    0, 0, 0, 0, 0, 0, 0
};


/* =============================================================
 * Parameter layout
 * ============================================================= */

static int setup_parameters(
    A2LiteBF592 *m)
{
    int p = 0;
    int i;

    m->rechannel = &m->q[p];
    p += 3;

    for (i = 0; i < A2LITE_LAYERS; ++i)
    {
        int conv_count = K[i] * 9;

        m->conv[i] = &m->q[p];
        p += conv_count;

        m->conv_bias[i] = &m->q[p];
        p += 3;

        m->mixin[i] = &m->q[p];
        p += 3;

        m->l1[i] = &m->q[p];
        p += 9;

        m->l1_bias[i] = &m->q[p];
        p += 3;
    }

    m->head = &m->q[p];
    p += 48;

    m->head_bias = &m->q[p];
    p++;

    m->head_scale = &m->q[p];
    p++;

    return p == A2LITE_PARAMETER_COUNT ? 0 : -1;
}


/* =============================================================
 * History layout
 * ============================================================= */

static int setup_history(
    A2LiteBF592 *m)
{
    int i;
    int offset = 0;

    for (i = 0; i < A2LITE_LAYERS; ++i)
    {
        int size;

        size =
            ((int)K[i] - 1) *
            (int)D[i] + 1;

        m->history_offset[i] =
            (uint16_t)offset;

        m->history_size[i] =
            (uint16_t)size;

        m->history_pos[i] = 0;

        offset += size;
    }

    return offset == A2LITE_HISTORY_SAMPLES
        ? 0
        : -1;
}


/* =============================================================
 * Integer helpers
 * ============================================================= */

static int32_t sat16(
    int32_t x)
{
    if (x > 32767)
        return 32767;

    if (x < -32768)
        return -32768;

    return x;
}


static int32_t sat32(
    int64_t x)
{
    if (x > 2147483647LL)
        return 2147483647L;

    if (x < -2147483648LL)
        return -2147483648L;

    return (int32_t)x;
}


/*
 * Exact:
 *
 * round_div_away_from_zero()
 */
static int32_t round_div_q14(
    int64_t x)
{
    if (x >= 0)
        return (int32_t)(
            (x + 8192) / 16384
        );

    return -(int32_t)(
        ((-x) + 8192) / 16384
    );
}


/*
 * Exact division by 100 for LeakyReLU.
 */
static int32_t leaky_relu(
    int32_t x)
{
    if (x >= 0)
        return x;

    if (x <= -50)
        return -((-x + 50) / 100);

    return 0;
}


/*
 * Arithmetic scaling with round-half-away-from-zero.
 *
 * shift is zero for the current model, but this is kept because
 * the BF592 runtime must implement the reference semantics.
 */
static int32_t shift_round(
    int64_t x,
    unsigned shift)
{
    int64_t divisor;
    int64_t half;

    if (shift == 0)
        return sat32(x);

    divisor = 1LL << shift;
    half = divisor >> 1;

    if (x >= 0)
        return sat32((x + half) / divisor);

    return sat32(-((-x + half) / divisor));
}


/* =============================================================
 * History access
 * ============================================================= */

static inline int16_t *
history_ptr(
    A2LiteBF592 *m,
    int layer,
    int position)
{
    return
        &m->history[
            (m->history_offset[layer] + position * 3)
        ];
}


static void history_push(
    A2LiteBF592 *m,
    int layer,
    const int16_t x[3])
{
    uint16_t pos =
        m->history_pos[layer];

    int16_t *dst =
        history_ptr(
            m,
            layer,
            pos
        );

    dst[0] = x[0];
    dst[1] = x[1];
    dst[2] = x[2];

    pos++;

    if (pos >= m->history_size[layer])
        pos = 0;

    m->history_pos[layer] = pos;
}


/*
 * delay=0 -> current sample
 * delay>0 -> previous sample
 */
static inline const int16_t *
history_get(
    const A2LiteBF592 *m,
    int layer,
    int delay)
{
    int pos;
    int size;

    size =
        m->history_size[layer];

    pos =
        (int)m->history_pos[layer]
        - 1
        - delay;

    if (pos < 0)
    {
        pos %= size;

        if (pos < 0)
            pos += size;
    }

    return
        &m->history[
            m->history_offset[layer]
            + pos * 3
        ];
}


/* =============================================================
 * Initialization
 * ============================================================= */

int a2lite_bf592_init(
    A2LiteBF592 *m,
    const int16_t *parameters)
{
    if (!m || !parameters)
        return -1;

    memset(
        m,
        0,
        sizeof(*m)
    );

    memcpy(
        m->q,
        parameters,
        sizeof(m->q)
    );

    if (setup_parameters(m) != 0)
        return -2;

    if (setup_history(m) != 0)
        return -3;

    a2lite_bf592_reset(m);

    return 0;
}


/* =============================================================
 * Reset
 * ============================================================= */

void a2lite_bf592_reset(
    A2LiteBF592 *m)
{
    if (!m)
        return;

    memset(
        m->history,
        0,
        sizeof(m->history)
    );

    memset(
        m->head_history,
        0,
        sizeof(m->head_history)
    );

    memset(
        m->history_pos,
        0,
        sizeof(m->history_pos)
    );

    m->head_pos = 0;
}


/* =============================================================
 * One layer
 * ============================================================= */

static void process_layer(
    A2LiteBF592 *m,
    int layer,
    const int16_t input[3],
    int16_t condition,
    int16_t output[3],
    int32_t activated[3])
{
    int out_ch;
    int in_ch;
    int tap;

    const int kernel =
        K[layer];

    const int dilation =
        D[layer];

    const unsigned shift =
        LAYER_SHIFT[layer];

    /*
     * Current sample becomes available at delay zero.
     */
    history_push(
        m,
        layer,
        input
    );


    /*
     * ---------------------------------------------------------
     * Convolution + bias + condition mixin
     * ---------------------------------------------------------
     */

    for (out_ch = 0;
         out_ch < 3;
         ++out_ch)
    {
        int32_t acc;

        acc =
            (int32_t)m->conv_bias[layer][out_ch]
            * A2LITE_Q_SCALE;

        for (tap = 0;
             tap < kernel;
             ++tap)
        {
            int delay =
                (kernel - 1 - tap)
                * dilation;

            const int16_t *x =
                history_get(
                    m,
                    layer,
                    delay
                );

            const int16_t *w =
                &m->conv[layer][tap * 9];

            /*
             * Matrix layout:
             *
             * tap * 9
             * + in_channel * 3
             * + out_channel
             */

            acc +=
                (int32_t)w[out_ch]
                * (int32_t)x[0];

            acc +=
                (int32_t)w[3 + out_ch]
                * (int32_t)x[1];

            acc +=
                (int32_t)w[6 + out_ch]
                * (int32_t)x[2];
        }


        /*
         * CRITICAL A2-Lite operation:
         *
         * conv + bias + mixin * condition
         */
        acc +=
            (int32_t)m->mixin[layer][out_ch]
            * (int32_t)condition;


        /*
         * INT32 BF592 normalization path.
         */
        acc =
            shift_round(
                acc,
                shift
            );


        {
            int32_t z;

            z =
                round_div_q14(
                    acc
                );

            z =
                leaky_relu(
                    z
                );

            activated[out_ch] =
                z;
        }
    }


    /*
     * ---------------------------------------------------------
     * 1x1 residual
     * ---------------------------------------------------------
     */

    for (out_ch = 0;
         out_ch < 3;
         ++out_ch)
    {
        int32_t acc;

        const int16_t *w =
            m->l1[layer];

        acc =
            (int32_t)m->l1_bias[layer][out_ch]
            * A2LITE_Q_SCALE;

        acc +=
            (int32_t)w[out_ch]
            * activated[0];

        acc +=
            (int32_t)w[3 + out_ch]
            * activated[1];

        acc +=
            (int32_t)w[6 + out_ch]
            * activated[2];

        acc =
            shift_round(
                acc,
                shift
            );

        {
            int32_t residual =
                round_div_q14(acc);

            output[out_ch] =
                (int16_t)sat16(
                    (int32_t)input[out_ch]
                    + residual
                );
        }
    }
}


/* =============================================================
 * Main streaming sample
 * ============================================================= */

int16_t a2lite_bf592_process(
    A2LiteBF592 *m,
    int16_t input)
{
    int ch;
    int layer;

    int16_t x[3];
    int16_t next[3];

    int32_t activated[3];

    int32_t head_source[3];

    /*
     * ---------------------------------------------------------
     * Rechannel
     * ---------------------------------------------------------
     */

    for (ch = 0; ch < 3; ++ch)
    {
        int32_t v =
            round_div_q14(
                (int32_t)m->rechannel[ch]
                * (int32_t)input
            );

        x[ch] =
            (int16_t)sat16(v);
    }


    /*
     * ---------------------------------------------------------
     * Sum of all 23 layer activations.
     *
     * This is NOT the final layer output.
     *
     * The 2.6 reference explicitly builds:
     *
     *     layer_activation_sum[c] += activated[c]
     *
     * for every layer.
     * ---------------------------------------------------------
     */

    head_source[0] = 0;
    head_source[1] = 0;
    head_source[2] = 0;


    for (layer = 0;
         layer < A2LITE_LAYERS;
         ++layer)
    {
        process_layer(
            m,
            layer,
            x,
            input,
            next,
            activated
        );

        head_source[0] += activated[0];
        head_source[1] += activated[1];
        head_source[2] += activated[2];

        x[0] = next[0];
        x[1] = next[1];
        x[2] = next[2];
    }


    /*
     * ---------------------------------------------------------
     * Head ring buffer
     * ---------------------------------------------------------
     */

    {
        uint16_t pos =
            m->head_pos;

        int64_t acc;

        m->head_history[pos][0] =
            head_source[0];

        m->head_history[pos][1] =
            head_source[1];

        m->head_history[pos][2] =
            head_source[2];


        /*
         * head bias is Q2.14, so convert to accumulator domain.
         */
        acc =
            (int64_t)(*m->head_bias)
            * A2LITE_Q_SCALE;


        /*
         * 16 taps × 3 channels.
         */
        for (int tap = 0;
             tap < A2LITE_HEAD_KERNEL;
             ++tap)
        {
            int hp =
                (int)pos
                - (A2LITE_HEAD_KERNEL - 1 - tap);

            if (hp < 0)
                hp += A2LITE_HEAD_KERNEL;

            const int32_t *src =
                m->head_history[hp];

            const int16_t *w =
                &m->head[tap * 3];

            acc +=
                (int64_t)w[0]
                * (int64_t)src[0];

            acc +=
                (int64_t)w[1]
                * (int64_t)src[1];

            acc +=
                (int64_t)w[2]
                * (int64_t)src[2];
        }


        /*
         * Advance head ring.
         */
        pos++;

        if (pos >= A2LITE_HEAD_KERNEL)
            pos = 0;

        m->head_pos = pos;


        /*
         * Q4.28 -> Q2.14
         */
        {
            int32_t y =
                round_div_q14(acc);

            /*
             * Head scale.
             */
            y =
                round_div_q14(
                    (int64_t)y
                    * (int64_t)(*m->head_scale)
                );

            return
                (int16_t)sat16(y);
        }
    }
}